### ISSUE TITLE
s3 link?

### ISSUE THREAD

**Issue by RMHogervorst** [opensanctions/yente#128]
hi there team, you can add files to yente with a file link or a url. Would a S3 link also work?

**Comment by pudo** [comment]
It'd be possible to add boto support, but before we consider that: what would be wrong with using a pre-signed URL for a file in a bucket? That would seem about the same level of complexity as injecting AWS credentials into the yente container etc. etc.

**Comment by RMHogervorst** [comment]
Excellent! That solves my issue
