### ISSUE TITLE
index ready time

### ISSUE THREAD

**Issue by AndreiD** [opensanctions/yente#133]
Hello

Running on a 8core 8gb ram system... since 30min ago

curl http://localhost:8000/readyz
{"detail":"Index not ready."}

anyone knows aproximatley how much time it takes to finish it?

Thank you

**Comment by pudo** [comment]
That's too much time. Can you access the log stream for the yente container and share it here?

**Comment by AndreiD** [comment]
it's finished. took about 1h

**Comment by pudo** [comment]
Just to follow up here: 

* Did you enable the statements API? That thing takes forever, the entities should be much faster. 
* Maybe consider upping the memory available to ElasticSearch a bit (in `docker-compose.yml`, `ES_JAVA_OPTS`). For your spec, I'd dedicate almost half your memory to the index - also for better runtime performance.

**Comment by AndreiD** [comment]
Thanks alot for the help and this repo.
