### ISSUE TITLE
Unable to connect to elastic search

### ISSUE THREAD

**Issue by majid-rehman** [opensanctions/yente#202]
I have followed the Readme and tried to run docker-compose up, But it is failing on this error. 

**Connection error caused by: ClientConnectorError(Cannot connect to host index:9200 ssl:default [Connection refused])**

[warning  ] Node <AiohttpHttpNode(http://index:9200)> has failed for 11 times in a row, putting on 30 second timeout [elastic_transport.node_pool] 
app_1    | 2023-01-27T15:40:30.004014Z [error] Cannot connect to ElasticSearch: ConnectionError('Cannot connect to host index:9200 ssl:default [Connection refused]', errors=(ConnectionError('Cannot connect to host index:9200 ssl:default [Connection refused]', errors=(ClientConnectorError(ConnectionKey(host='index', port=9200, is_ssl=False, ssl=None, proxy=None, proxy_auth=None, proxy_headers_hash=3119452235181044255)

**Comment by pudo** [comment]
My intuition here is that for some reason, ElasticSearch on your system failed to start. Can you check it's logs and see if there's any error message there? `docker-compose logs index`

**Comment by majid-rehman** [comment]
@pudo logs are normal, no error

> index    | {"@timestamp":"2023-01-31T07:54:39.129Z", "log.level": "INFO",  "current.health":"GREEN","message":"Cluster health status changed from [YELLOW] to [GREEN] (reason: [shards started [[yente-entities-all-00220230131003038][0]]]).","previous.health":"YELLOW","reason":"shards started [[yente-entities-all-00220230131003038][0]]" , "ecs.version": "1.2.0","service.name":"ES_ECS","event.dataset":"elasticsearch.server","process.thread.name":"elasticsearch[index][masterService#updateTask][T#1]","log.logger":"org.elasticsearch.cluster.routing.allocation.AllocationService","elasticsearch.cluster.uuid":"crK0-RHSQS6dTpzAt6c-oA","elasticsearch.node.id":"yh9h4aQXQv-dr03aWLxW0Q","elasticsearch.node.name":"index","elasticsearch.cluster.name":"opensanctions-index"}

**Comment by majid-rehman** [comment]
you can see I can curl localhost:9200

> [ec2-user@ip-10-42-10-141 yente]$ curl localhost:9200
> {
>   "name" : "index",
>   "cluster_name" : "opensanctions-index",
>   "cluster_uuid" : "crK0-RHSQS6dTpzAt6c-oA",
>   "version" : {
>     "number" : "8.3.2",
>     "build_type" : "docker",
>     "build_hash" : "8b0b1f23fbebecc3c88e4464319dea8989f374fd",
>     "build_date" : "2022-07-06T15:15:15.901688194Z",
>     "build_snapshot" : false,
>     "lucene_version" : "9.2.0",
>     "minimum_wire_compatibility_version" : "7.17.0",
>     "minimum_index_compatibility_version" : "7.0.0"
>   },
>   "tagline" : "You Know, for Search"
> }

**Comment by pudo** [comment]
Very weird - then it almost certainly looks like a docker issue. Are you just running a normal `docker-compose up` to get things going? No docker swarm etc.?

**Comment by majid-rehman** [comment]
I make it run somehow, It was an elastic search issue, I just increase resources on my VM

**Comment by pudo** [comment]
Hello Fritz! Can you let me know what resource allocations you have for Elastic? If you're running docker, does it have a writeable volume mounted for the data?
