### ISSUE TITLE
The default index refresh interval is "every minute past every 2nd hour" instead of the desired "every 2nd hour."

### ISSUE THREAD

**Issue by coastalberry** [opensanctions/yente#468]
The current default value for `CRONTAB = env_str("YENTE_CRONTAB", "* */2 * * *")` in `yente/settings.py`  sets the index refresh interval to "every minute past every 2nd hour" instead of the desired "every 2nd hour:" https://github.com/opensanctions/yente/blame/4dc0dfb7ac61c91b132a7f3f3519d3eb3538490c/yente/settings.py#L100.

Fix: Replace the default value with `0 */2 * * *` or similar.

On a related note, the [yente settings documentation](https://www.opensanctions.org/docs/yente/settings/) also still states that the default refresh interval is 30 minutes.

**Comment by pudo** [comment]
Damn that was dumb. I've updated the docs, @SimonThordal can you update the setting to be a 0 at the start or something? We could even generate a random minute so that we don't see a thundering herd on the data site :)

**Comment by pudo** [comment]
Fixed.
